[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.7.1",
    "mkdocstrings[python]>=1.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
